language: c
compiler:
    - gcc
    - clang
script: sudo apt-get install libprotobuf-c0-dev protobuf-c-compiler && git submodule update --init && cd jnxlibc && cmake . && make && sudo make install && cd ../ && C_INCLUDE_PATH=/usr/include/google cmake . -DRUN_TESTS=ON && make
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
    irc:
        channels:
            - "chat.freenode.net#jnxlibc"
    on_sucess: [always]
    on_failure: [always] # default: always
