language: c
compiler:
    - gcc
    - clang
before_script: sudo apt-get install libprotobuf-c0-dev protobuf-c-compiler
script: git submodule update --init && cmake . -DRUN_TESTS=ON && make
notifications:
    email:
        recipients:
            - alexsimonjones@gmail.com
        on_sucess: [never]
        on_failure: [always] # default: always
    irc:
        channels:
            - "chat.freenode.net#jnxlibc"
    on_sucess: [always]
    on_failure: [always] # default: always
