/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: session_transport.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "session_transport.pb-c.h"
void   session_transport__init
                     (SessionTransport         *message)
{
  static SessionTransport init_value = SESSION_TRANSPORT__INIT;
  *message = init_value;
}
size_t session_transport__get_packed_size
                     (const SessionTransport *message)
{
  assert(message->base.descriptor == &session_transport__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t session_transport__pack
                     (const SessionTransport *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &session_transport__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t session_transport__pack_to_buffer
                     (const SessionTransport *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &session_transport__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SessionTransport *
       session_transport__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SessionTransport *)
     protobuf_c_message_unpack (&session_transport__descriptor,
                                allocator, len, data);
}
void   session_transport__free_unpacked
                     (SessionTransport *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &session_transport__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor session_transport__field_descriptors[1] =
{
  {
    "guid",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SessionTransport, n_guid),
    offsetof(SessionTransport, guid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_transport__field_indices_by_name[] = {
  0,   /* field[0] = guid */
};
static const ProtobufCIntRange session_transport__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor session_transport__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "session_transport",
  "SessionTransport",
  "SessionTransport",
  "",
  sizeof(SessionTransport),
  1,
  session_transport__field_descriptors,
  session_transport__field_indices_by_name,
  1,  session_transport__number_ranges,
  (ProtobufCMessageInit) session_transport__init,
  NULL,NULL,NULL    /* reserved[123] */
};
