/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: session_object.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "session_object.pb-c.h"
void   session_object__init
                     (SessionObject         *message)
{
  static SessionObject init_value = SESSION_OBJECT__INIT;
  *message = init_value;
}
size_t session_object__get_packed_size
                     (const SessionObject *message)
{
  assert(message->base.descriptor == &session_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t session_object__pack
                     (const SessionObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &session_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t session_object__pack_to_buffer
                     (const SessionObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &session_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SessionObject *
       session_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SessionObject *)
     protobuf_c_message_unpack (&session_object__descriptor,
                                allocator, len, data);
}
void   session_object__free_unpacked
                     (SessionObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &session_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor session_object__field_descriptors[2] =
{
  {
    "guid",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SessionObject, n_guid),
    offsetof(SessionObject, guid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsa_public_key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SessionObject, rsa_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_object__field_indices_by_name[] = {
  0,   /* field[0] = guid */
  1,   /* field[1] = rsa_public_key */
};
static const ProtobufCIntRange session_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor session_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "session_object",
  "SessionObject",
  "SessionObject",
  "",
  sizeof(SessionObject),
  2,
  session_object__field_descriptors,
  session_object__field_indices_by_name,
  1,  session_object__number_ranges,
  (ProtobufCMessageInit) session_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
