/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_peer_2eproto__INCLUDED
#define PROTOBUF_C_peer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Peer Peer;


/* --- enums --- */


/* --- messages --- */

struct  _Peer
{
  ProtobufCMessage base;
  ProtobufCBinaryData guid;
  char *host_address;
  char *user_name;
};
#define PEER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&peer__descriptor) \
    , {0,NULL}, NULL, NULL }


/* Peer methods */
void   peer__init
                     (Peer         *message);
size_t peer__get_packed_size
                     (const Peer   *message);
size_t peer__pack
                     (const Peer   *message,
                      uint8_t             *out);
size_t peer__pack_to_buffer
                     (const Peer   *message,
                      ProtobufCBuffer     *buffer);
Peer *
       peer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   peer__free_unpacked
                     (Peer *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Peer_Closure)
                 (const Peer *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor peer__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_peer_2eproto__INCLUDED */
